### ISSUE TITLE
Usage with androidx

### ISSUE THREAD

**Issue by Firefds** [skydoves/ColorPickerPreference#15]
I'm trying to use the library with androidx library and I'm getting casting errors.
I hope you can migrate this library to work with Androidx

` android.view.InflateException: Binary XML file line #7: Error inflating class com.skydoves.colorpickerpreference.ColorPickerPreference
        at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:249)
        at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:277)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:344)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:377)
        at sb.firefds.pie.firefdskit.FirefdsKitActivity$NavigationBarSettingsFragment.onCreatePreferences(FirefdsKitActivity.java:565)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
        at sb.firefds.pie.firefdskit.FirefdsPreferenceFragment.onCreate(FirefdsPreferenceFragment.java:29)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2523)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:834)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1196)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1079)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:118)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1850)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1808)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1715)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:143)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.ClassCastException: com.skydoves.colorpickerpreference.ColorPickerPreference cannot be cast to androidx.preference.Preference
        at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:242)
        at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:277) 
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:344) 
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346) 
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157) 
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109) 
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216) 
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:377) 
        at sb.firefds.pie.firefdskit.FirefdsKitActivity$NavigationBarSettingsFragment.onCreatePreferences(FirefdsKitActivity.java:565) 
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160) 
        at sb.firefds.pie.firefdskit.FirefdsPreferenceFragment.onCreate(FirefdsPreferenceFragment.java:29) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2523) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:834) 
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1196) 
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1079) 
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:118) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1850) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1808) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1715) 
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:143) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7045) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) `

**Comment by skydoves** [comment]
@Firefds 
It is solved on version 1.0.8!
Thank you for your issue :)

**Comment by Firefds** [comment]
@skydoves this works great on it's own now!
But when I want to use it along side the ColorPickerView there are still issues .
[ColorPickerViewLog.txt](https://github.com/skydoves/ColorPickerPreference/files/3002011/ColorPickerViewLog.txt)

**Comment by skydoves** [comment]
@Firefds 
New 2.0.0 version published!
It is using [ColorPickerView](https://github.com/skydoves/ColorPickerView) library totally except a `ColorPickerPreference`. 👍

**Comment by Firefds** [comment]
@skydoves great job! Works nicely.
